# Generated by Django 5.1.3 on 2024-11-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empleadorol',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rol',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='api.departamento'),
        ),
        migrations.AddIndex(
            model_name='empleadorol',
            index=models.Index(fields=['empleado', 'es_rol_principal'], name='idx_empleado_rol_principal'),
        ),
        migrations.AddConstraint(
            model_name='empleadorol',
            constraint=models.UniqueConstraint(fields=('empleado', 'rol'), name='unique_empleado_rol'),
        ),
    ]
