# Generated by Django 5.1.3 on 2024-12-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='stock_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
