# Generated by Django 5.1.3 on 2024-12-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_inventario_idx_inventario_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
