# Generated by Django 5.1.3 on 2024-11-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_empleadorol_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, help_text='Fecha de salida de la empresa', null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha real de inicio de trabajo', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(help_text='Fecha en que se firma el contrato'),
        ),
    ]
