# Generated by Django 5.1.3 on 2024-12-07 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producto_cantidad_actual_producto_stock_maximo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_dni', message='El DNI debe contener 8 dígitos numéricos', regex='^\\d{8}$')], verbose_name='Documento de Identidad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
